version: "3"

services:  
        redis:
                image: redis:latest
                hostname: redis

        web:
                build:
                        context: .
                        dockerfile: Dockerfile
                restart: always
                hostname: web
                user: calcus
                command: ./scripts/run_web.sh
                expose:
                        - 8000
                volumes:
                        - .:/calcus 
                        - ./docker/inchi:/binaries/other
                links:
                        - redis
                env_file:
                        - ./.env
                depends_on:
                        - postgres
        nginx:
                image: nginx:latest
                ports:
                        - "8080:8080"
                volumes:
                        - ./docker/nginx/:/etc/nginx/conf.d
                        - ./static:/static
                        - .:/calcus
                depends_on: 
                        - web        
        celery_main:
                build:
                        context: .
                        dockerfile: Dockerfile
                user: calcus
                command: ./scripts/run_celery_main.sh
                volumes:
                        - .:/calcus
                        - ./docker/inchi:/binaries/other
                env_file:
                        - ./.env
                links:
                        - redis
                depends_on:
                        - redis
        celery_comp:
                build:
                        context: .
                        dockerfile: Dockerfile
                user: calcus
                command: ./scripts/run_celery_comp.sh
                volumes:
                        - .:/calcus
                        - ./docker/inchi:/binaries/other
                        - ${CALCUS_GAUSSIAN}:/binaries/g16
                        - ${CALCUS_ORCA}:/binaries/orca
                        - ${CALCUS_XTB}:/binaries/xtb
                        - ${CALCUS_OPENMPI}/bin:/binaries/openmpi
                        - ${CALCUS_OPENMPI}/lib:/usr/lib/openmpi
                env_file:
                        - ./.env
                links:
                        - redis
                depends_on:
                        - redis
        cluster:
                build:
                        context: .
                        dockerfile: Dockerfile
                user: calcus
                command: ./scripts/run_cluster_daemon.sh
                env_file:
                        - ./.env
                volumes:
                        - .:/calcus
                links:
                        - web
                depends_on:
                        - redis
        postgres:
                image: postgres:11-bullseye
                restart: always
                user: "${UID}:${GID}"
                volumes:
                        - ./data:/var/lib/postgresql/data/:rw
                env_file:
                        - ./.env
                environment:
                        - PGDATA=./var/lib/postgresql/data/
                        - POSTGRES_USER=calcus
                        - POSTGRES_DB=calcus


