version: "3.4"

services:  
        redis:
                image: redis:latest
                hostname: redis

        web:
                build:
                        context: .
                        dockerfile: Dockerfile
                        target: calcus_dev
                hostname: web
                user: "${UID}:${GID}"
                expose:
                        - 8000
                depends_on:
                        - redis
                        - slurm
                volumes:
                        - scratch:/calcus/scratch
                        - ./frontend/tests/cache:/calcus/cache
                env_file:
                        - ./.env
                environment:
                        - CALCUS_TEST=True
                links:
                        - slurm
                        - redis
        slurm:
                build:
                        context: ./docker/slurm
                        dockerfile: Dockerfile
                hostname: slurm
                volumes:
                        - ./frontend/tests/cache:/calcus/cache/
                command: /home/slurm/run_slurm.sh
                env_file:
                        - ./.env
                environment:
                        - CALCUS_TEST=True
        selenium:
                container_name: selenium
                image: selenium/standalone-chrome:latest
                ports:
                        - "4444:4444"
                        - "5900:5900"
                links:
                        - web
                shm_size: '1gb' # Necessary to ensure that selenium does not crash
        cluster:
                build:
                        context: .
                        dockerfile: Dockerfile
                        target: calcus_dev
                restart: always
                user: "${UID}:${GID}"
                command: ./scripts/run_cluster_daemon.sh
                environment:
                        - CALCUS_TEST=True
                        - IS_TEST_CLUSTER_DAEMON=True
                volumes:
                        - scratch:/calcus/scratch
                env_file:
                        - ./.env
                links:
                        - web
                depends_on:
                        - redis

        postgres:
                image: postgres:11-bullseye
                restart: always
                user: "${UID}:${GID}"
                volumes:
                        - ./data:/var/lib/postgresql/data/:rw
                env_file:
                        - ./.env
                environment:
                        - PGDATA=./var/lib/postgresql/data/
                        - POSTGRES_USER=calcus
                        - POSTGRES_DB=calcus

volumes:
  scratch:
