version: "3"

services:  
        redis:
                image: redis:latest
                hostname: redis

        web:
                build:
                        context: .
                        dockerfile: Dockerfile
                hostname: web
                user: calcus
                expose:
                        - 8000
                volumes:
                        - .:/calcus 
                        - ${CALCUS_INCHI}:/binaries/other
                        - ${CALCUS_GAUSSIAN}:/binaries/g16
                        - ${CALCUS_ORCA}:/binaries/orca
                        - ${CALCUS_XTB}:/binaries/xtb
                        - ${CALCUS_OPENMPI}/bin:/binaries/openmpi
                        - ${CALCUS_OPENMPI}/lib:/usr/lib/openmpi
                depends_on:
                        - redis
                        - slurm
                env_file:
                        - ./.env
                environment:
                        - CALCUS_TEST=True
                links:
                        - slurm
                        - redis
        slurm:
                build:
                        context: ./docker/slurm
                        dockerfile: Dockerfile
                hostname: slurm
                command: /home/slurm/run_slurm.sh
                volumes:
                        - .:/calcus 
                        - ./docker/slurm/calcus:/home/slurm/calcus 
                        - ${CALCUS_INCHI}:/home/slurm/other
                        - ${CALCUS_GAUSSIAN}:/home/slurm/g16
                        - ${CALCUS_ORCA}:/home/slurm/orca
                        - ${CALCUS_XTB}:/home/slurm/xtb
                        - ${CALCUS_OPENMPI}/bin:/home/slurm/openmpi
                        - ${CALCUS_OPENMPI}/lib:/usr/lib/openmpi
                env_file:
                        - ./.env
                environment:
                        - CALCUS_TEST=True
        selenium:
                container_name: selenium
                image: selenium/standalone-chrome-debug:latest
                #user: calcus
                volumes:
                        - ${CALCUS_INCHI}:/binaries/other
                ports:
                        - "4444:4444"
                        - "5900:5900"
                links:
                        - web

