version: "3.4"

services:  
        redis:
                image: redis:latest
                hostname: redis

        web:
                build:
                        context: .
                        dockerfile: Dockerfile
                        target: calcus_dev
                hostname: web
                user: "${UID}:${GID}"
                expose:
                        - 8000
                depends_on:
                        - redis
                        - slurm
                env_file:
                        - ./.env
                environment:
                        - CALCUS_TEST=True
                links:
                        - slurm
                        - redis
        slurm:
                build:
                        context: ./docker/slurm
                        dockerfile: Dockerfile
                hostname: slurm
                command: /home/slurm/run_slurm.sh
                env_file:
                        - ./.env
                environment:
                        - CALCUS_TEST=True
        selenium:
                container_name: selenium
                image: selenium/standalone-chrome:latest
                #user: calcus
                ports:
                        - "4444:4444"
                        - "5900:5900"
                links:
                        - web
                shm_size: '1gb' # Necessary to ensure that selenium does not crash
        postgres:
                image: postgres:11-bullseye
                restart: always
                user: "${UID}:${GID}"
                volumes:
                        - ./data:/var/lib/postgresql/data/:rw
                env_file:
                        - ./.env
                environment:
                        - PGDATA=./var/lib/postgresql/data/
                        - POSTGRES_USER=calcus
                        - POSTGRES_DB=calcus


